### ISSUE TITLE
Cannot transform files marked as external

### ISSUE THREAD

**Issue by AndrewLeedham** [wessberg/rollup-plugin-ts#102]
### Feature Use Case
I created a repro and the readme explains the use case: https://github.com/AndrewLeedham/repros/tree/master/packages/rollup-plugin-ts-workspaces

### Feature Proposal
Allow a hook to be run to transform the collected TS SourceFiles before TypeScript processes them. The `before` hook seems to run after TS has linked everything.

_Disclaimer: I am very new to the topic of TS transformers and the TS compiler API. So I am probably suggesting something that is not possible here..._

**Comment by AndrewLeedham** [comment]
If any is curious about this I found a workaround: https://github.com/AndrewLeedham/repros/commit/f7698074182e1da93513cd8a12ec5ce99370c0b3

Essentially just creating a rollup load plugin to swap the imports.

@wessberg I think my issue stemmed here from a lack of understanding of how/when rollup-plugin-ts does things. Perhaps it would be useful to include an explainer in the readme? Describing what the plugin uses to create typings, e.g. `transform` won't effect the output but `load` will.

**Comment by AndrewLeedham** [comment]
Hmmm actually it would seem that `load` works fine unless the module is marked as "external" which in my case it is. Any thoughts on this @wessberg ?

**Comment by AndrewLeedham** [comment]
I have created a minimal repro for this. This is potentially a TS feature that does not exist. But it seems I would need to transform an imported file which is not a `SourceFile`: https://repl.it/@AndrewLeedham56/rollup-plugin-ts-external-repro#transformer.js

Some more context: https://stackoverflow.com/questions/62838264/typescript-transformers-transform-imported-file

**Comment by wessberg** [comment]
Hi Andrew. I responded [here](https://github.com/microsoft/TypeScript/issues/39634#issuecomment-664841471):

> Just FYI: TypeScript Custom Transformers can be a bit surprising in that they run during the emit phase and as such any transformations applied in a before transformer won't actually have an impact on the declarations that will be generated by TypeScript. For example, you may intuitively expect that, say, renaming a ClassDeclaration from "Foo" to "Bar" would carry over to the declarations, but since the type checking phase is decoupled from the emit phase in TypeScript, it won't. Instead, if you want to transform the declarations with the Compiler APIs, you can use the afterDeclarations transformer hook as part of your Custom Transformer logic. With the beforementioned example, that would mean that you'd have to use the updateClassDeclaration method of the NodeFactory API and provide a new name to the ClassDeclaration while transforming declarations in an afterDeclarations hook.
>
> As for external files, TypeScript is structurally founded in _Programs_ which contain _SourceFiles_, and TypeScript won't run your transformers for files that aren't part of that Program.

This is a major gotcha, and not many many people know this.

In the context of this issue, that means that if what you want to do is transform the source files before the emit phase (so that the changes are reflected in the declarations produced by TypeScript), the best solution currently is to apply whatever transformations you want to make in another rollup plugin placed _before_ `rollup-plugin-ts`. You would then not have the Compiler APIs to work with, and I can see why you want that.

Let me mark this as a feature suggestion for an "intelligent" `before` hook that is actually reflected in the declarations. I would find that very useful :-) 

However, I don't agree that it would make sense to call this hook with SourceFiles that are external to the program.

**Comment by AndrewLeedham** [comment]
@wessberg Thanks for the response. I came up with a workaround, where I use a stub module to act as the JSX library import, then I can transform the `SourceFile` to use the proper library and leave the external modules as is.

The "intelligent" before hook seems like a cool idea, not sure it is useful for my needs, but seems useful nonetheless. Personally I think TS just needs some documentation for custom transformers.

**Comment by wessberg** [comment]
Hey there. Upon further reflection, and given it has been a few years, I've come to think this is actually best solved with another plugin placed before `rollup-plugin-ts` that applies whatever transformations you intend, rather than the intelligent `before` hook we discussed. Since your original issue was related to external files anyway, and that it wasn't actually part of the proposed solution, and since you found a workaround, I hope you're OK with me closing this issue. If not, feel free to comment again.
