### ISSUE TITLE
Function declaration not created when using export { default as foo } from '/path/to/foo'

### ISSUE THREAD

**Issue by AndrewLeedham** [wessberg/rollup-plugin-ts#129]
- Version: 1.3.8
- Rollup Version: 2.34.2
- Node Version: 12.16.1
- Does it work with `tsc`: Yes

### Reproduction
I created a minimal repro which shows the results from both rollup-plugin-ts and tsc.
https://repl.it/@AndrewLeedham56/rollup-plugin-ts-namespace-repro

### Expected Behavior
The declaration file to have both a function and namespace type, like the tsc output here: https://repl.it/@AndrewLeedham56/rollup-plugin-ts-namespace-repro#dist/tsc/foo.d.ts

This seems to be caused by `export { default as Foo } from './foo';` as compiling `./foo.ts` directly works as expected (I also tried `export * from './foo'` but that worked fine): https://repl.it/@AndrewLeedham56/rollup-plugin-ts-namespace-repro#dist/rollup-foo/foo.d.ts

### Actual Behavior
It only has the namespace: https://repl.it/@AndrewLeedham56/rollup-plugin-ts-namespace-repro#dist/rollup/index.d.ts

**Comment by wessberg** [comment]
Hey Andrew,

Sorry for the late reply! This was due to a problem where ModuleDeclarations/NamespaceDeclaration could sometimes not be traced correctly, so their bindings would be deconflicted by mistake, and then the function was tree-shaken away.

I've since fixed this problem and will release a new version on NPM shortly.
I hope you found a workaround in the meantime :-)
