### ISSUE TITLE
Error: 'default' is not exported by 'tyepof.js', imported by 'possibleConstructorReturn.js'

### ISSUE THREAD

**Issue by roydukkey** [wessberg/rollup-plugin-ts#150]
- Version: 1.4.1
- Rollup Version: 2.56.3
- Operating System and version (if applicable): MacOS 11.5.2 (20G95)
- Node Version (if applicable): 16.6.1
- Does it work with `tsc` (if applicable): Yes (`yarn build:tsc`)

### Reproduction

I have a repo which I'd like to keep private for the time being, so I have sent an invitation to you. Without pre-exposing my work, I'll help you capture the issue here in more detail however I can.

1. `yarn`
2. `yarn build`

### Expected Behavior

1. All packages should compile in the mono repo.
2. I have read this [explainer](https://github.com/wessberg/rollup-plugin-ts/blob/HEAD/documentation/explainer/why_is_babel-plugin-transform-runtime_and_tslib_included_by_default.md), but the solutions at the bottom don't appear to resolve this issue.
3. Your help is much appreciated. Thank you!

### Actual Behavior

Error:
```
./src/index.ts → ./dist/build.js...
created ./dist/build.js in 2.4s

./src/index.ts → ./dist/build.umd.js...
created ./dist/build.umd.js in 1s

src/sub-package-1/index.ts → src/sub-package-1/dist/build.js...
created src/sub-package-1/dist/build.js in 1.4s

src/sub-package-1/index.ts → src/sub-package-1/dist/build.umd.js...
created src/sub-package-1/dist/build.umd.js in 1s

src/sub-package-2/index.ts → src/sub-package-2/dist/build.js...
created src/sub-package-2/dist/build.js in 975ms

src/sub-package-2/index.ts → src/sub-package-2/dist/build.umd.js...
created src/sub-package-2/dist/build.umd.js in 869ms

src/sub-package-3/index.ts → src/sub-package-3/dist/build.js...
[!] Error: 'default' is not exported by node_modules/@babel/runtime/helpers/typeof.js, imported by node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js (1:7)
1: import _typeof from "@babel/runtime/helpers/typeof";
          ^
2: import assertThisInitialized from "./assertThisInitialized.js";
3: export default function _possibleConstructorReturn(self, call) {
Error: 'default' is not exported by node_modules/@babel/runtime/helpers/typeof.js, imported by node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js
    at error (/.../node_modules/rollup/dist/shared/rollup.js:151:30)
    at Module.error (/.../node_modules/rollup/dist/shared/rollup.js:10059:16)
    at Module.traceVariable (/.../node_modules/rollup/dist/shared/rollup.js:10444:29)
    at ModuleScope.findVariable (/.../node_modules/rollup/dist/shared/rollup.js:9227:39)
    at FunctionScope.findVariable (/.../node_modules/rollup/dist/shared/rollup.js:3654:38)
    at ChildScope.findVariable (/.../node_modules/rollup/dist/shared/rollup.js:3654:38)
    at Identifier.bind (/.../node_modules/rollup/dist/shared/rollup.js:4591:40)
    at CallExpression.bind (/.../node_modules/rollup/dist/shared/rollup.js:2886:23)
    at CallExpression.bind (/.../node_modules/rollup/dist/shared/rollup.js:7214:15)
    at BinaryExpression.bind (/.../node_modules/rollup/dist/shared/rollup.js:2886:23)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wessberg** [comment]
Hey there! First of all, thank you a million times for your sponsorship. That is very kind of you, and it helps me prioritize maintaining open source projects like this. I'm grateful, so I also looked into your issue and fixed it immediately as part of [v1.4.2](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.4.2)

The problem wasn't actually `rollup-plugin-ts`, but rather that the ESM-based `@babel/runtime/helpers/esm/possibleConstructorReturn.js` file included an import to `@babel/runtime/helpers/typeof.js`, which is CJS-based, which I'm certain is simply a bug, since `@babel/runtime/helpers/esm/typeof.js` also exists in the same folder, which is ESM-based.

Rollup doesn't understand CommonJS by default, so when it sees an import of a named binding from a CommonJS-based module, such as it did when it evaluated `node_modules/@babel/runtime/helpers/typeof.js`, it will throw an exception, unless you add a plugin to rollup that teaches it how to understand CommonJS modules. There's an official one called [`rollup-plugin-commonjs`](https://www.npmjs.com/package/@rollup/plugin-commonjs) that I would recommend here.

But I worked around these things anyway by adding a workaround directly within `rollup-plugin-ts` that rewrites these imports from `node_modules/@babel/runtime/helpers/typeof.js` to `node_modules/@babel/runtime/helpers/esm/typeof.js` when inside an ESM-helper.

I've tested the fix on your code base, and everything built correctly, so I'll close this issue. Thanks again!
