### ISSUE TITLE
Warning about invalid `pnpm` during `yarn install`

### ISSUE THREAD

**Issue by alejandroclaro** [wessberg/rollup-plugin-ts#168]
- Version:
- Rollup Version: 2.67.2
- Node Version (if applicable): 14.18.3
- Yarn: 1.22.17

### Reproduction

If only `yarn` and `npm` are installed, the following warning occurs during `yarn install`:

```
warning rollup-plugin-ts@2.0.5: The engine "pnpm" appears to be invalid.
```
### Expected Behavior

Installation should not report any warning.

### Actual Behavior

During installation, a warring occurs.

**Comment by wessberg** [comment]
After digging into this a bit, it would seem that [this is caused by yarn v1](https://github.com/yarnpkg/yarn/issues/7560) warning about engines it doesn't know about, in this case [pnpm](https://pnpm.io/). They later fixed it [in this commit](https://github.com/devoto13/yarn/commit/10bb170eda9d491bb73db21538f84054685aebe8). This information can be useful for `pnpm` users, and won't produce any warnings for npm users either. As it has been fixed since, and yarn 2 does  _not_ produce such a warning, I'm not going to remove this engine from the package.json, as it is useful for pnpm users, such as myself.
