### ISSUE TITLE
ES2020 dynamic star exports not compiled correctly

### ISSUE THREAD

**Issue by archfz** [wessberg/rollup-plugin-ts#175]
- Version: 2.0.5
- Rollup Version: 2.70.1
- Operating System and version (if applicable): ubuntu
- Node Version (if applicable): 14.x.x
- Does it work with `tsc` (if applicable): yes

### Reproduction

ES2020 named star exports (https://github.com/microsoft/TypeScript/issues/4813) are not compiled correctly with this plugin. Using same tsconfig tsc compiles it correctly.

1. Create a project where you have star exports. `index.ts`
   ```ts
   export * as a from 'a';
   export * as b from 'b';
   ```
2. `tsconfig.json`
    ```json
    {
      "compilerOptions": {
        "module": "es2020",
        "target": "es2020",
        "lib": ["esnext"],
        "skipLibCheck": true,
        "strictNullChecks": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "moduleResolution": "node",
        "isolatedModules": true
      }
    }
    ```
3. Observe final `index.js` to be:
   ```js
   import * as index from 'a';
   export { index as a };
   import * as index$1 from 'b';
   export { index$1 as b };
   ```

### Expected Behavior

Final `index.js` is:
```js
   export * as a from 'a';
   export * as b from 'b';
```

**Comment by wessberg** [comment]
Hi there.

How [Module Namespace Exports](https://github.com/tc39/proposal-export-ns-from) are handled is not related to the behavior of `rollup-plugin-ts`, but is handled instead directly by Rollup.

The code in your example [is exactly what Rollup generates without any plugins](https://rollupjs.org/repl/?version=2.70.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBhcyUyMGElMjBmcm9tJTIwJ2EnJTNCJTVDbmV4cG9ydCUyMColMjBhcyUyMGIlMjBmcm9tJTIwJ2InJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

The reason is that Rollup by default generates code that is compliant with ES2019 and below by default. I'm going to close this issue, as it has no relation to this plugin.
