### ISSUE TITLE
The `@babel/plugin-transform-runtime` is not found

### ISSUE THREAD

**Issue by tunnckoCore** [wessberg/rollup-plugin-ts#37]
Why we need this? As long as I know it should be used as devDependency, so why when generating production builds we need it? 

And should I add it in my preset too? And one side question: does the plugin reads `babel.config.js` when found **AND** you have `babelConfig` option set? My assumption is it's not? Just for verification.

**Comment by wessberg** [comment]
@babel/plugin-transform-runtime is added to and merged with the users provided Babel config if it doesn't already include it. The reason why it is added is to move shared Babel helpers into import statements rather than duplicating them inline such that they can be shared across chunks without duplication.

The reason why you may get the error in the issue title is if you depend on another library that depends strictly on a _different_ version of `@babel/plugin-transform-runtime` (such as `tsdx` does).

As for the side-question: If you override the `babelConfig` option, your `babel.config.js` file won't be resolved, so your assumption is correct 😊

**Comment by tunnckoCore** [comment]
Yea, I get that, it's some optimization but that means it's required to include it as depedency on you production, right? Which kind of conflicts with the one of the reasons of why you are bundling in the first place.

So, there's no way to disable that at all?

**Comment by wessberg** [comment]
Not quite sure what you mean about the production thing 😊? If what you are asking is if in the end there'll be imports from `@babel/plugin-transform-runtime` inside of the bundle, then no, unless you've added @babel/plugin-transform-runtime` to Rollup's `external` option in which case Rollup will preserve the import statements, like with anything else. It is there because if it wasn't, Babel helpers would be duplicated across chunks, so it serves the purpose of keeping bundles as small as possible.

I'm sorry you feel like this plugin does too much. I respectfully disagree, this is neither Babel nor Typescript - this is trying to combine them in a batteries-included way and let each tool do what it's best at, but some options of Babel and Typescript doesnt make sense in combination with Rollup. Now, I'm open to making it possible to opt out of default plugins, and there's a PR for this where we can continue on with the discussion.

**Comment by tunnckoCore** [comment]
> inside of the bundle, then no, unless you've explicitly added

That was exactly the case. It was in the bundle and I got issue about. And if I remember correctly, no I didn't added it as `external`.

The point about devDependency was that i think that this plugin shouldn't be in the production output right? So it's normal to include it only as devDepdendency.

> do agree that it should be possible to opt out of default plugins, and there's a PR for this where we can continue on with the discussion.

Yup I think that's a good move.

**Comment by wessberg** [comment]
> The point about devDependency was that i think that this plugin shouldn't be in the production output right? So it's normal to include it only as devDependency.

If `@babel/plugin-transform-runtime` was only a `devDependency` of `rollup-plugin-ts`, it wouldn't be installed when you do `npm install @wessberg/rollup-plugin-ts` :-) Making it a devDependency would break every time anyone attempted to build anything with rollup-plugin-ts and `transpiler: "babel"` given that `@babel/plugin-transform-runtime` would be unresolvable. Actually, the title of this issue is exactly what would happen :-).

Let me explain it with an example:

If you do something like:

```typescript
typeof foo
```

Then, as I'm sure you already know, Babel may transform it into something like:

```typescript
function _typeof(obj) {
// ...
}

typeof foo === "undefined" ? "undefined" : _typeof(foo);
```

Let's say we didn't use `@babel/plugin-transform-runtime`. Then, for each file that includes a `typeof` we run though Rollup, the `_typeof` helper would be duplicated. So if you write `typeof` in 3 files, you get 3 duplications of that helper.

The end bundle may end up looking like this:

```typescript
function _typeof(obj) { /* ... */}
typeof foo === "undefined" ? "undefined" : _typeof(foo);
function _typeof$1(obj) { /* ... */}
typeof bar === "undefined" ? "undefined" : _typeof$1(bar);
function _typeof$2(obj) { /* ... */}
typeof baz === "undefined" ? "undefined" : _typeof$2(baz);
```

That's unfortunate. Here goes the same example, but with `@babel/plugin-transform-runtime`.
Again, if you have a file that looks like this:

```typescript
typeof foo
```

...Then babel would transform it into something like this:

```typescript
import _typeof from "@babel/runtime/helpers/esm/typeof.js";

typeof foo === "undefined" ? "undefined" : _typeof(foo);
```

Now, as long as Rollup is able to resolve the file called `@babel/runtime/helpers/esm/typeof.js` from the disk - it will only be resolvable if it is a dependency, _not_ a devDependency -, and as long as you don't explicitly mark it as external, here's how the bundle will come out:


```typescript
function _typeof(obj) { /* ... */}
typeof foo === "undefined" ? "undefined" : _typeof(foo);
typeof bar === "undefined" ? "undefined" : _typeof(bar);
typeof baz === "undefined" ? "undefined" : _typeof(baz);
```

So, no runtime dependencies. If the import(s) from babel's runtime is left in, there will have been problems with resolving it such as can be the case with some package managers when multiple packages depend on conflicting versions of the same package.

**Comment by tunnckoCore** [comment]
Nope nope nope. Not what I meant at all. Anyway.

**Comment by tunnckoCore** [comment]
Example https://github.com/tunnckoCore/opensource/issues/70. And not I didn't have anything put in `external`.

**Comment by wessberg** [comment]
Well, for what it's worth, I definitely agree with you that it should never happen unless you explicitly want it, and this plugin should do it's best to avoid it from ever happening.

**Comment by tunnckoCore** [comment]
It's not example repo. And the thing is long gone. ;) 

I couldn't find the changes I did for that specific issue i linked.
