### ISSUE TITLE
Generics disappear from output types

### ISSUE THREAD

**Issue by Marsup** [wessberg/rollup-plugin-ts#58]
Hi,

I've created a small repro for a problem we're having on an actual project, see here: https://repl.it/@Marsup/rollup-plugin-ts-bug.

The resulting types (in dist/input.d.ts) are missing the generics information for the Set on line 3, what I'd expect is `f1: Set<number | boolean>` like in the original one. I have to mention there was a warning during the build: `'typescript-collections' is imported by input2.ts, but could not be resolved – treating it as an external dependency`, which is fine for us since we don't want to bundle node modules in, would it have an influence over generics loss?

I'd be willing to help but I'm not sure where to start and if I can help further, but do let me know if you want me to run some more tests on our actual project.

Thanks!

**Comment by wessberg** [comment]
Hey there. This issue will be resolved when I'm releasing the next minor version based on the [experiment](https://github.com/wessberg/rollup-plugin-ts/tree/experiment) branch soon. However, an arguably better way to handle this kind of thing with Rollup is to mark the module as external in your Rollup config to inform Rollup that it is meant to be a runtime dependency, rather than producing a warning.

**Comment by wessberg** [comment]
This has been fixed as part of [v1.2.0](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.0). Happy New Year!

**Comment by Marsup** [comment]
Looks like it is, thanks a lot, and happy new year to you too! 😄
