### ISSUE TITLE
Bad types for symbols and repeated functions

### ISSUE THREAD

**Issue by Marsup** [wessberg/rollup-plugin-ts#69]
Hi again,

Continuing on my previous example (https://repl.it/@Marsup/rollup-plugin-ts-bug), I've enriched it with some bugs that appeared with the 1.2.x release.

The generated code is fine, but the types are not. As you can see the destructuring seems to introduce some $0 suffix rename of the parameter, maybe to avoid naming conflicts? Also, the symbol imports don't seem to work. In our case the symbol comes from an external lib but it seems to fail with local symbols as well.

I may have time later to investigate, unless someone else gets to it first.

**Comment by wessberg** [comment]
Hey there.

Nice catch! This was a fun one to track down and fix. The Symbol thing was related to TypeScript applying special handling for unique symbols inside computed property names in Property- and MethodSignatures in ambient contexts. That lead to the tree-shaker not counting it as a reference.

The $0 deconflicted suffix was due to the deconflicting logic not creating a new lexical environment for FunctionTypeNodes, like it currently does for FunctionDeclarations and FunctionExpressions.

It has been fixed and released in [v1.2.6](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.6).

**Comment by Marsup** [comment]
Wow, that was very much not straightforward! Thanks for the quick fix!
