### ISSUE TITLE
Cannot use version 1.2

### ISSUE THREAD

**Issue by zhaparoff** [wessberg/rollup-plugin-ts#70]
Tested all versions from 1.2.0 up to latest. No one work for me anymore.

Versions 1.2.2 and up failing during rollup build with different errors.

The latest (1.2.4) fails on
`export type TypeA = "string1" | "string2";` with `Unexpected token 'type'`

Version 1.2.1 allows souces to be built, but the result code does not work in IE 11. It produces some shorthand notation for object declarations, which IE does not support.

**Comment by wessberg** [comment]
Hey there. There's a few things in there, some I assume is declaration related and some I assume is related to the emitted JavaScript not targeting the ECMA version you've defined. In any case, I'll need far more details on all of it to be able to proceed from here.

Please share with me your configs and preferably one or more repros. I'll also need to know what your environment is since often times problems are isolated to Windows or certain TypeScript versions.

**Comment by wessberg** [comment]
Hey again. I've released [v1.2.5](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.5) in which some bugs related to mistakenly adding ambient files to the Rollup graph has been resolved. Will you please test and see if this issue has been fixed?

**Comment by wessberg** [comment]
Hey there. I'm gonna assume that this problem was resolved since v1.2.5. If not, feel free to write back to me, and I'll reopen the issue.
