### ISSUE TITLE
Configuring this plugin per-output?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [wessberg/rollup-plugin-ts#74]
So, I'd like to have multiple outputs that use different `rollup-plugin-ts` configurations, for instance:

1. A FireFox-only build, using a `browserslist: "last 5 Firefox versions"` config, producing output to `dist/bundle.ff.js` …
2. Both minified and non-minified builds, to `dist/bundle.js` and `dist/bundle.min.js`,

so on, so forth. Unfortunately, it looks like this plugin is configured only once, at the root-level? I'd like to be able to do something like this:

```js
export default {
   input: 'src/interface.ts',
   plugins: [
      resolve(),
      ts({
         transpiler: 'babel',
      }),
   ],
   output: [
      {
         file: 'dist/interface.js',
         format: 'cjs',
         exports: 'default',
      },
      {
         file: 'dist/interface.esm.js',
         format: 'esm',
      },
      {
         file: 'dist/interface.ff.js',
         format: 'esm',
         plugins: [
            ts({
               browserslist: 'last 5 Firefox versions',
            }),
         ],
      },
   ],
}
```

Is anything like this possible?

**Comment by wessberg** [comment]
Hi there! Thanks for writing.

`rollup-plugin-ts` relies on the following build-time hooks from Rollup's lifecycle: `options`, `resolveId`, `load`,  and`transform`. It is a a relatively new thing that Rollup supports per-output plugins, and they're great, but only useful for things that doesn't rely on manipulating Rollup's module graph, and/or transforming individual files (which is needed for transforming TypeScript syntax into valid JavaScript before passing it back to Rollup and Acorn).

A great example of something that can be a per-output plugin would be something like minification - it only needs to run per-chunk, rather than per-file and doesn't need to manipulate the module graph.

Your use case is great and very common, but you will need to do something like this instead:

```javascript

const createBaseConfig = browserslist => ({
  input: 'src/interface.ts',
  plugins: [
    resolve(),
    ts({
      transpiler: 'babel',
      browserslist
    }),
  ],
});

export default [
  {
    ...createBaseConfig(),
    output: [
      {
        file: 'dist/interface.js',
        format: 'cjs',
        exports: 'default',
      },
      {
        file: 'dist/interface.esm.js',
        format: 'esm',
      }
    ]
  },
  {
    ...createBaseConfig('last 5 Firefox versions'),
    output: {
      file: 'dist/interface.ff.js',
      format: 'esm'
    }
  }
];
```
