### ISSUE TITLE
Optional Chaining don't work with TypeScript as parser

### ISSUE THREAD

**Issue by cschroeter** [wessberg/rollup-plugin-ts#75]
I have discovered a curious error. If I use Optional Chaining in combination with TypeScript as parser, I get an error.

```ts
export interface User {
  name?: string
  age: number
}

export const myUser: User = { age: 30 }
console.log(myUser.name?.toString())
```

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/index.ts (6:25)
4: }
5: 
6: export const myUser: User = { age: 30 }
                            ^
7: console.log(myUser.name?.toString())
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

You can find an simple example repo here https://github.com/cschroeter/bug-rollup-ts/

**Comment by wessberg** [comment]
Hey there. The reason why you experience this is because the `target` inside your `tsconfig` is `esnext`. This means that TypeScript will preserve optional chaining in the emitted code that the plugin transforms your source code into. In fact, it is part of `es2020`, so if you don't want TypeScript to preserve optional chaining, you'll have to change your target to `es2019` or earlier. Rollup, which tries to parse it into an Acorn AST then has a parsing error since the Acorn version Rollup relies on doesn't yet support optional chaining/nullish coalescing syntax.

However, if you'd like to preserve the optional chaining/nullish coalescing syntax, then you can install [this acorn plugin](https://github.com/rockon999/acorn-optional-chaining) and provide it to Rollup:

```javascript
import optionalChaining from 'acorn-optional-chaining';

export default {
    // … other options …
    acornInjectPlugins: [
        optionalChaining()
    ]
};
```

Rollup will eventually support the syntax natively. Thanks for using `rollup-plugin-ts`!

**Comment by cschroeter** [comment]
This was the most detailed and fastest answer I ever got from an OpenSource project. Thank you so much
