### ISSUE TITLE
Why are babel versions pinned?

### ISSUE THREAD

**Issue by ckknight** [wessberg/rollup-plugin-ts#76]
As per https://github.com/wessberg/rollup-plugin-ts/blob/master/package.json#L80-L89, the versions seem to be pinned to very specific babel versions. Why not use `~` or `^`?

**Comment by wessberg** [comment]
Hey there! Thanks for bringing it up. We can revert the change now. I had to temporarily lock the version dependencies since we relied on some internal Babel helpers for getting the location of a config file that had some breaking changes between minor versions that broke `rollup-plugin-ts`. The solution was to pin the versions while I refactored the code to not depend on babel internals, which has been done now.

I'll unpin the versions in the next release!

**Comment by wessberg** [comment]
The versions have been unpinned again in [v1.2.14](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.14).
