### ISSUE TITLE
Interface that shares name with namespace being dropped

### ISSUE THREAD

**Issue by ggoodman** [wessberg/rollup-plugin-ts#81]
I'm loving this module so thanks @wessberg. I'm using it to take a slice out of the vscode repo and repackage as its own module.

*index.ts*:

```typescript
export interface Something {
  type: string;
}

export namespace Something {
  export function forUseCase(): Something {
    // Something useful
  }
}
```

The resulting bundle's `.d.ts` does not include the `Something` interface, only the namespace.

My use-case is in [ggoodman/ts-primitives](https://github.com/ggoodman/ts-primitives) which pulls vscode source in a build script and produces a slice of the overall repo using rollup in-memory.

The issue is that for consuming libraries, the interface `CancellationToken` is being stripped from here https://github.com/microsoft/vscode/blob/f8014d495791145f1fac93cc0283737878272129/src/vs/base/common/cancellation.ts#L9-L25

Note that just below is `export namespace CancellationToken`. You can see what is being produced [on unpkg](https://unpkg.com/ts-primitives@2.1.1/dist/index.d.ts).

**Comment by wessberg** [comment]
Hey there! Thanks for using this library. I'm glad you like it.
I do have a question that I hope you can help me out with.

You're doing `export interface Something` _and_ `export namespace Something`. These two exported bindings conflict with each other. I guess that is a mistake?

Here's the declaration output `rollup-plugin-ts` v1.2.16 generates from your example, if I assign unique names to the interface (`Something1`) and namespace (`Something2`):

```typescript
interface Something1 {
    type: string;
}
declare namespace Something2 {
    function forUseCase(): Something1;
}
export { Something1, Something2 };
```

**Comment by wessberg** [comment]
Hey there. Thanks for submitting this issue! I'm glad you like the library.

What you are actually touching on here is a fundamental aspect of `rollup-plugin-ts` which is that it will _deconflict_ identically named bindings inside the same scope, because it is based on the fundamental assumption that the identifiers may originate from multiple SourceFiles that are brought together and may be identically named.

However, TypeScript also supports [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), and this library attempts to figure out when declaration merging or function overloading is happening (in which case it must not deconflict) or not.

In this particular case, I think what's happening is that `rollup-plugin-ts` mistakenly attempts to deconflict the interface from the NameSpace which leads to something like this:

```typescript
interface Something {
    type: string;
}
declare namespace Something$0 {
    function forUseCase(): Something$0;
}
export { Something };
```

And this is not actually correct. So to fix this, I'll need to revisit declaration merging vs deconflicting.

**Comment by wessberg** [comment]
This has been fixed in [v1.2.17](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.17).
I've tested a build based on cloning your `ts-primitives` library, and the `CancellationToken` is indeed preserved in the output.

**Comment by ggoodman** [comment]
Can conflict identification be tweaked to understand that type-only and value-only symbols can't collide?

**Comment by wessberg** [comment]
Thing is, type-only symbols _can_ collide if they are brought together from multiple SourceFiles that will be bundled together in the same chunk.

For example:

```typescript
// index.ts
export * from "./foo";

// foo.ts
import {Bar} from "./bar";
type Prop = string;
export class Foo extends Bar {
  someProp: Prop;
}

// bar.ts
type Prop = number;
export class Bar {
  someOtherProp: Prop;
}
```

In this example, `foo.ts` and `bar.ts` both declare a TypeAliasDeclaration, `Prop`, but they are both local to their individual modules and needs to treated as separate symbols.

When bringing them together in a bundled declaration file, however, the two symbols must be deconflicted to avoid collisions.

```typescript
type Prop = number;
declare class Bar {
  someOtherProp: Prop;
}
type Prop$0 = string;
declare class Foo extends Bar {
  someProp: Prop$0;
}

export { Foo };
```

To solve this issue, I added logic to the lexical environment tracking that also tracked which SourceFile a symbol was originally declared within. Declarations will be merged if they were originally declared in the same SourceFile, and otherwise deconflicted.

**Comment by wessberg** [comment]
Wait, maybe I misunderstood your question. Do you have an example of some code in which type and value symbols are identically named and should be collision-free, but are deconflicted by `rollup-plugin-ts`? 🙂
