### ISSUE TITLE
Error: "[name] is not exported by [module]" but types are installed

### ISSUE THREAD

**Issue by CSchulz** [wessberg/rollup-plugin-ts#84]
It seems that there is an issue while resolving a module from node_modules and the types are seperated from the project.

```
npx  rollup -c rollup.config.ts

src/index.ts → dist/index.js, dist/index.es5.js...
(!) Plugin node-resolve: preferring built-in module 'util' over local alternative at 'util',pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'crypto' over local alternative at 'crypto', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'buffer' over local alternative at 'buffer', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
util (imported by node_modules/inherits/inherits.js, util?commonjs-external)
crypto (imported by node_modules/brorand/index.js, crypto?commonjs-external)
buffer (imported by node_modules/bn.js/lib/bn.js, buffer?commonjs-external)
[!] Error: 'ec' is not exported by node_modules/elliptic/lib/elliptic.js, imported by node_modules/webcrypto-liner/build/index.es.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/webcrypto-liner/build/index.es.js (13:9)
```

Repro:  
https://repl.it/repls/YellowgreenDopeyBsddaemon

**Comment by wessberg** [comment]
Hey there. Thanks for the repro! However, this issue is unrelated to `rollup-plugin-ts`. If you simply comment out `ts` from the plugins array in your rollup config, you'll find that you get the exact same error.

Instead, it is related to Rollup not being able to resolve a named exported binding inside the file `node_modules/elliptic/lib/elliptic.js` called `ec`. This is due to it being a CommonJS module, something that Rollup doesn't natively understand. Even though you are using `@rollup/plugin-commonjs`, a plugin that does its best at rewriting CommonJS modules into valid ESM for interoperability with Rollup, it is not always able to automatically rewrite modules into valid ESM, as is the case here.

You can [see this comment](https://github.com/wessberg/rollup-plugin-ts/issues/78) I've made on another issue with more detailed instructions and some suggestions as to what you can do.

Since this is unrelated to this plugin, I'm closing this issue.
