### ISSUE TITLE
Are there minimal examples?

### ISSUE THREAD

**Issue by stared** [wessberg/rollup-plugin-ts#87]
My goal is to generate `.ems.js` , `.min.js` and `.d.ts` files for a typescript repository.

README file lists a few examples of  `rollup.config.js`. I was unable to run them, possibly due to some 'obvious' assumptions about other file structures. (E.g it even misses run command. Neither `cross-env` or `rollup` command are recognized.)

Are there minimal working examples (i.e. full repositories), to that use rollup-plugin-ts?

**Comment by wessberg** [comment]
Hey there! Thanks for checking out this plugin. I'm curious to understand what you mean with your points about `cross-env` and `rollup` not being recognized, and how that relates to this plugin? These needs to be in your path, or alternatively installed in your project-local `node_modules` folder. Alternatively, you can run them with `npx` (such as `npx rollup`). In any case, if you need assistance with how to configure Rollup, or how to generate a boilerplate Rollup project, or run it from NPM scripts, there are several resources on the subject online. There's quite a few minimal examples in the readme, the smallest of which is to simply add `rollup-plugin-ts` to your plugins array to Rollup without configuring anything. Is there something special you are looking to know more about?

I think what you are looking for is a Rollup boilerplate project that works in your local development environment. If you have a working environment and a way to build with Rollup, adding `rollup-plugin-ts` to that will be as easy as installing it and adding it to your config ☺️

**Comment by stared** [comment]
I already use other plugins for TypeScript, so for me it is far from obvious how to change that.

See e.g. https://github.com/Quantum-Game/bra-ket-vue/blob/master/build/rollup.config.js  where I sue `babel` for TypeScript, but it does not generate types declarations (to be clear: I made it from a template, not by hand, see https://github.com/team-innovation/vue-sfc-rollup/issues/35). In another repository, it took me some trial and error (https://github.com/Quantum-Game/quantum-tensors/pull/16) to create Rollup config for TS https://github.com/Quantum-Game/quantum-tensors/blob/master/rollup.config.js (this time without `babel`, but with `rollup-plugin-typescript2`; I generate file declarations with `tsc`).

For install instructions - all in all, I expect peer dependencies to be listed explicitly in the `yarn add --dev` line. Less guessing what id included as a dependency, what one needs to install separately.

**Comment by wessberg** [comment]
Hey there, thanks for writing back with a follow-up comment.

I'm well aware that it can be a bit puzzling to put together the many tools that goes into web development. One major reason why I built this plugin is to make a part of that process much simpler and more _batteries-included_. It's great that you describe what is - and what isn't - obvious to you as someone getting into Rollup. So thanks for your input.

I will consider adding a note to the README about `rollup` and `typescript` being peerDependencies. I'm somewhat hesitant due to the following:

1. Package managers such as Yarn and NPM will notify upon installation of missing peer dependencies. So, you as a library consumer will always know what's missing during installation.

2. Given that this is a plugin _for_ Rollup, I do think it is contextually obvious or at least acceptably implicit that you'll need to install Rollup to go with it. If you are going to install a Rollup plugin, chances are you already installed Rollup or know that you are about to.

Regarding the docs in general, they concern themselves strictly with what this specific plugin does, and not what else you can do with Rollup, so I think it is only natural that they are restricted to just that. There are examples in there showing how you can combine TypeScript with Babel and Browserslists, all of which are simple. Is there a specific guide you feel like is missing, or do you have any suggestions to how one of the current ones might be expanded to help you understand it better?

**Comment by stared** [comment]
I understand that people may come from various backgrounds of experience.
However, if the goal is "batteries-included", some explicit examples (i.e. no single "obvious" line). Plus, code does not lie.

Myself, I have 7 years of on-and-off experience with JavaScripts, and build systems are still a mystery. Moreover, as you know perfectly, the system changes.  Just a few days ago one of my CI tests failed because a new update of Node broke some parts of the new-ish babel (~2months old release).  In this case, if something does not work - it is easier to track if there is some wrong with the script, conflict with other tools (it happened to me so many times, that a particular chain of tools didn't work),  or say - it doesn't work with the newest Node.

For Rollup, well - for quite some time I didn't needed that (as I created apps and visualizations, not libraries). 

"To use a simple solution, you need to understand more a complicated solution" may give a higher barrier of entry. In particular - when you asked me the first time about my Rollup config it was **a chicken and egg problem* - I didn't have one! I was not able to configure it with TypeScript! It took quite some time to set it up (many examples and tutorials were not working, for one reason or another).

> Package managers such as Yarn and NPM will notify upon installation of missing peer dependencies. So, you as a library consumer will always know what's missing during installation.

Frankly, it is a bad practice for any tutorial ("instruction is incomplete but you will get some warnings (among many others, so you may miss them), so I guess you will know what to").  It can be anything "assumes you have typescript and rollup in your dependencies", or IMHO much better 

```
yarn add --dev rollup typescript @wessberg/rollup-plugin-ts
```

(BTW: you want it as a dev dependency, right?)

To be clear - it is your project, and up to you how you present it. :) 

Also, I don't expect a Rollup tutorial. But tested minimalistic repo examples.

Side note: in another, Python package, I decided to forgo any tutorial or docs (well, mostly lack of time), and use only fully functional examples (https://github.com/stared/livelossplot/blob/master/examples/keras.ipynb). People were able to grab it quickly, with almost no entry barrier

**Comment by wessberg** [comment]
Thanks for your feedback. I've adressed it in the following way:

- Added `--save-dev` and `--dev` options to installation instructions for npm/pnpm and Yarn respectively.
- Added a [subsection](https://github.com/wessberg/rollup-plugin-ts#peer-dependencies) inside the `install` section where I explicitly mention the peerDependencies.
- Added a [Starter Templates](https://github.com/wessberg/rollup-plugin-ts#starter-templates) section in the README that includes a list of ready-to-use boilerplate templates on [repl.it](https://repl.it).

I'm closing this issue. If there are other things you'd like to better better explained, or if you experience any problems, feel free to comment again or open another issue.

**Comment by stared** [comment]
Thank you a lot, it is exactly things I had in mind! :)

This interactive examples, with visible outputs, is very interesting. Finally, I understand the basic setup, and I hope it will be more accessible for others as well!
