### ISSUE TITLE
External types information

### ISSUE THREAD

**Issue by Marsup** [wessberg/rollup-plugin-ts#92]
Hi!

Currently the definitions that are emitted can potentially contain imports from external `@types`, which is exactly what I want, but I was wondering if there was a way to know which ones, in the same way that rollup exposes an `imports` property for its chunks. I could try and detect if there's an `@types/*` based on the imports of the chunks, but that seems a bit hazardous. Do you know of a way to achieve that properly?

Thanks.

**Comment by wessberg** [comment]
Hi there. Thanks for your question. Since we already have some hooks, I guess we can look into adding an additional hook for extracting relevant metadata about generated declarations, such as what module specifiers are being imported for each declaration chunk.

Considering a code splitting scenario, we might have something like:

- `./a.d.ts` depends on `c.d.ts`
- `./b.d.ts` depends on `./c.d.ts`

And let's say `./a.d.ts` depends on `some-external-package`. Then we could probably emit something like this via a hook:

```typescript
[
  {
      fileName: "a.d.ts",
      imports: ["c.d.ts", "some-external-package"],
      // ...
  },
  {
      fileName: "b.d.ts",
      imports: ["c.d.ts"],
      // ...
  }
]
```

Is it something like this you're looking for?

**Comment by wessberg** [comment]
Hey there. I've implemented this feature as part of [v1.2.33](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.33) and documented how to use it [here](https://github.com/wessberg/rollup-plugin-ts/#the-declarationstats-hook)

**Comment by Marsup** [comment]
This worked great! Thanks a lot! It might have been a bit easier if the types for this feature were exposed but I'm nitpicking :slightly_smiling_face:

**Comment by wessberg** [comment]
Hehe, that's quite alright. I'll make sure to export the relevant interfaces from the next release.
